[project]
name = "lab02-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pip>=25.1",
    "psycopg>=3.2.7",
    "sentence-transformers>=4.1.0",
    "sqlalchemy>=2.0.40",
    "transformers>=4.51.3",
]
