[project]
name = "lab02-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pgvector>=0.4.1",
    "pip>=25.1",
    "psycopg>=3.2.7",
    "sentence-transformers>=4.1.0",
    "sqlalchemy>=2.0.40",
    "transformers>=4.51.3",
]

[dependency-groups]
dev = [
    "ipywidgets>=8.1.6",
]
